apiVersion: v1
kind: Service
metadata:
  name: api-bancaria
  namespace: api-bancaria
spec:
  selector:
    app: api-bancaria
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30002
  type: NodePort
